language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - android-24
    - build-tools-24.0.2

sudo: false

notifications:
  email: false

before_install:
    - chmod +x ./AssistanceSDK/gradlew

script:
    - ./AssistanceSDK/gradlew clean
    - ./AssistanceSDK/gradlew build

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'